/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.wbs.view;


import br.com.wbs.entity.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author willian
 */
public class TelaPrincipal extends javax.swing.JFrame {

   private Usuario usu;
   private String data;
   

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    public TelaPrincipal(Usuario usu) {

        initComponents();
        this.usu = usu;
        setIcon();
        data = getDataAtual();
        lbldata.setText(data);
        lblusu.setText(usu.getNome());
        desativaFuncoesDoSistema(usu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdeskPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblusu = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        itemUsu = new javax.swing.JMenuItem();
        itemCli = new javax.swing.JMenuItem();
        itemOs = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        itemServ = new javax.swing.JMenuItem();
        menAju = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbs/images/Sem título.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 290, -1));

        javax.swing.GroupLayout jdeskPrincipalLayout = new javax.swing.GroupLayout(jdeskPrincipal);
        jdeskPrincipal.setLayout(jdeskPrincipalLayout);
        jdeskPrincipalLayout.setHorizontalGroup(
            jdeskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jdeskPrincipalLayout.setVerticalGroup(
            jdeskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        getContentPane().add(jdeskPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 840));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bem Vindo!");
        jLabel2.setToolTipText("");

        lblusu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusu.setForeground(new java.awt.Color(255, 0, 0));
        lblusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusu.setText("Usuário");
        lblusu.setToolTipText("");

        lbldata.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldata.setText("Data");
        lbldata.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldata)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(lblusu, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(lbldata)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 260, 310));

        menCad.setText("Cadastro");
        menCad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemUsu.setText("Usuário");
        itemUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuActionPerformed(evt);
            }
        });
        menCad.add(itemUsu);

        itemCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemCli.setText("Cliente");
        menCad.add(itemCli);

        itemOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemOs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemOs.setText("OS");
        menCad.add(itemOs);

        jMenuBar1.add(menCad);

        menRel.setText("Relatórios");
        menRel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemServ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemServ.setText("Serviços");
        menRel.add(itemServ);

        jMenuBar1.add(menRel);

        menAju.setText("Ajuda");
        menAju.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemSobre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemSobre.setText("Sobre");
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menAju.add(itemSobre);

        jMenuBar1.add(menAju);

        menOpc.setText("Opções");
        menOpc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menOpc.add(itemSair);

        jMenuBar1.add(menOpc);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1244, 872));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
      TelaSobre tSobre = new TelaSobre();
      jdeskPrincipal.add(tSobre);
      tSobre.setVisible(true);
    }//GEN-LAST:event_itemSobreActionPerformed

    private void itemUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuActionPerformed
       TelaCadUsu cadUsu = new TelaCadUsu();
       jdeskPrincipal.add(cadUsu);
       cadUsu.setVisible(true);
    }//GEN-LAST:event_itemUsuActionPerformed

    
    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
      int opc = JOptionPane.showConfirmDialog(null,"Deseja sair do sistema?","Atenção" ,JOptionPane.YES_NO_CANCEL_OPTION);
      if(opc == JOptionPane.YES_OPTION){
          this.dispose();
         }
    }//GEN-LAST:event_itemSairActionPerformed

      public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/wbs/images/icone tela login.png")));
    }

    public String getDataAtual() {
        Calendar dataAtual = Calendar.getInstance();
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        String data = f.format(dataAtual.getTime());
        return data;
    }

    public void desativaFuncoesDoSistema(Usuario usu) {

        if (usu.getTipo().equals("usuário")) {
            menRel.setEnabled(false);
            itemUsu.setEnabled(false);
            lblusu.setForeground(Color.black);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCli;
    private javax.swing.JMenuItem itemOs;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemServ;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuItem itemUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdeskPrincipal;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lblusu;
    private javax.swing.JMenu menAju;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenu menRel;
    // End of variables declaration//GEN-END:variables
  
}
