/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.wbs.view;

import br.com.wbs.DAO.UsuarioDAO;
import br.com.wbs.entity.Usuario;
import br.com.wbs.util.ModeloTabelaUsuarios;
import java.math.BigInteger;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author willian
 */
public class TelaCadUsu extends javax.swing.JInternalFrame {

    private UsuarioDAO usuDao = new UsuarioDAO();

    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadUsu() {
        initComponents();
        txtId.setEditable(false);
        preencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jfFone = new javax.swing.JFormattedTextField();
        jfCelular = new javax.swing.JFormattedTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsu = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Usuários");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setText("Telefone");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel4.setText("Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jLabel5.setText("Celular");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel6.setText("Login");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        try {
            jfFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jfFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 141, -1));

        try {
            jfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jfCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 141, -1));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 208, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 208, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 534, -1));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selecione---", "Administrador", "usuário" }));
        getContentPane().add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 189, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 78, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Excluir");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbs/images/user-id-icon_34334 (3).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, 50));

        jtbUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbUsu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 398, 860, 280));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 50));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 100, 50));

        setBounds(0, 0, 921, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Usuario usu = carregarDadosDaTela();
        if (validar()) {
            boolean status = usuDao.salvar(usu);
            if (status) {
                limparCampos();
                preencherTabela();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (jtbUsu.getSelectedRow() != -1) {
            //System.out.println(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 0).toString());
            carregarCamposParaTela();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor selecione um usuário na tabela a baixo para editar!", "Atenção", 1);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (jtbUsu.getSelectedRow() != -1) {
            String usuario = jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 1).toString();

            int option = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o usuário "
                    + usuario + " ?", "Atenção!", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                //Pegando o conteudo da linha selecionada na coluna 0
                String id = jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 0).toString();
                UsuarioDAO usuDao = new UsuarioDAO();
                usuDao.deletar(Integer.parseInt(id));
                JOptionPane.showMessageDialog(null, "Usuário excluido com sucesso!");
                preencherTabela();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um usuário na tabela abaixo para fazer a exclusão.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        jtbUsu.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que pega todos os valores da linha selecionada na tabela e carrega
     * nos seus respectivos campos.
     */
    public void carregarCamposParaTela() {
        txtNome.setText(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 1).toString());
        jfFone.setText(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 2).toString());
        jfCelular.setText(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 6).toString());
        txtId.setText(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 0).toString());
        txtLogin.setText(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 3).toString());
        txtSenha.setText(jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 4).toString());
        String itemCbx = jtbUsu.getValueAt(jtbUsu.getSelectedRow(), 5).toString();
        for (int i = 0; i < cbxTipo.getItemCount(); i++) {
            if (itemCbx.equals(cbxTipo.getItemAt(i))) {
                cbxTipo.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * Método que pega todos os dados digitados nos campos da tela e seta em um
     * objeto Usuario.
     *
     * @return Retorna um Objeto Usuario
     */
    public Usuario carregarDadosDaTela() {
        Usuario usu = new Usuario();
        usu.setNome(txtNome.getText());
        usu.setFone(jfFone.getText());
        usu.setCelular(jfCelular.getText());
        usu.setLogin(txtLogin.getText());
        usu.setSenha(txtSenha.getText());
        usu.setTipo(cbxTipo.getSelectedItem().toString());
        String id = txtId.getText();
        if (!(id.equals(""))) {
            usu.setId(new BigInteger(id));

        }

        return usu;
    }

    public void limparCampos() {
        txtNome.setText(null);
        jfFone.setText(null);
        jfCelular.setText(null);
        txtId.setText(null);
        txtLogin.setText(null);
        txtSenha.setText(null);
        cbxTipo.setSelectedIndex(0);
    }

    public boolean validar() {
        boolean valida = false;
        if (txtNome.getText().equals(null) || txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo nome está em branco! Por favor preencha-o para prosseguir.", "Atenção", 1);
            txtNome.requestFocus();
        } else if (!validaCampoTelefone()) {
            JOptionPane.showMessageDialog(null, "O campo telefone está em branco! Por favor preencha-o para prosseguir.", "Atenção", 1);
            jfFone.requestFocus();
        } else if (!validaCampoCelular()) {
            JOptionPane.showMessageDialog(null, "O campo Celular está em branco! Por favor preencha-o para prosseguir.", "Atenção", 1);
            jfCelular.requestFocus();
        } else if (txtLogin.getText().equals(null) || txtLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo login está em branco! Por favor preencha-o para prosseguir.", "Atenção", 1);
            txtLogin.requestFocus();
        } else if (txtSenha.getText().equals(null) || txtSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo senha está em branco! Por favor preencha-o para prosseguir.", "Atenção", 1);
            txtSenha.requestFocus();
        } else if (!validaCampoTipo()) {
            JOptionPane.showMessageDialog(null, "Por favor selecione o tipo de usuário para prosseguir.", "Atenção", 1);
            cbxTipo.requestFocus();

        } else {
            valida = true;
        }
        return valida;
    }

    /**
     * *
     * Método que percorre toda a String e verifica se o campo telefone está
     * totalmente preenchido.
     *
     * @return Retorna um valor boolean.
     */
    public boolean validaCampoTelefone() {
        boolean validou = true;
        char c1;
        char c2 = ' ';
        for (int i = 0; i < jfFone.getText().length(); i++) {
            if (i >= 1 && i <= 2) {
                c1 = jfFone.getText().charAt(i);
                if (c1 == c2) {
                    validou = false;
                }
            } else if (i >= 5 && i <= 8) {
                c1 = jfFone.getText().charAt(i);
                if (c1 == c2) {
                    validou = false;
                }
            } else if (i >= 10 && i <= 13) {
                c1 = jfFone.getText().charAt(i);
                if (c1 == c2) {
                    validou = false;
                } else {
                    return validou;
                }
            }
        }
        return validou;
    }

    public boolean validaCampoCelular() {
        boolean validou = true;
        char c1;
        char c2 = ' ';
        for (int i = 0; i < jfCelular.getText().length(); i++) {
            if (i >= 1 && i <= 2) {
                c1 = jfCelular.getText().charAt(i);
                if (c1 == c2) {
                    validou = false;
                }
            } else if (i >= 6 && i <= 9) {
                c1 = jfCelular.getText().charAt(i);
                if (c1 == c2) {
                    validou = false;
                }
            } else if (i >= 11 && i <= 14) {
                c1 = jfCelular.getText().charAt(i);
                if (c1 == c2) {
                    validou = false;
                } else {
                    return validou;
                }
            }
        }
        return validou;
    }

    public boolean validaCampoTipo() {

        if (cbxTipo.getSelectedIndex() <= 0) {
            System.out.println("ITEM SELECIONADO" + cbxTipo.getSelectedItem().toString());
            return false;
        }

        return true;
    }

    public void preencherTabela() {
        ArrayList dados = new UsuarioDAO().buscaParaPreencherTabela();
        String[] colunas = {"iduser", "Nome", "Telefone", "Login", "Senha", "Tipo", "Celular"};
        ModeloTabelaUsuarios modelo = new ModeloTabelaUsuarios(dados, colunas);

        jtbUsu.setModel(modelo);

        jtbUsu.getColumnModel().getColumn(0).setPreferredWidth(60);
        jtbUsu.getColumnModel().getColumn(0).setResizable(false);
        jtbUsu.getColumnModel().getColumn(1).setPreferredWidth(250);
        jtbUsu.getColumnModel().getColumn(1).setResizable(false);
        jtbUsu.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtbUsu.getColumnModel().getColumn(2).setResizable(false);
        jtbUsu.getColumnModel().getColumn(3).setPreferredWidth(120);
        jtbUsu.getColumnModel().getColumn(3).setResizable(false);
        jtbUsu.getColumnModel().getColumn(4).setPreferredWidth(120);
        jtbUsu.getColumnModel().getColumn(4).setResizable(false);
        jtbUsu.getColumnModel().getColumn(5).setPreferredWidth(90);
        jtbUsu.getColumnModel().getColumn(5).setResizable(false);
        jtbUsu.getColumnModel().getColumn(6).setPreferredWidth(110);
        jtbUsu.getColumnModel().getColumn(6).setResizable(false);

        jtbUsu.getTableHeader().setReorderingAllowed(false);
        jtbUsu.setAutoResizeMode(jtbUsu.AUTO_RESIZE_OFF);

        jtbUsu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jfCelular;
    private javax.swing.JFormattedTextField jfFone;
    private javax.swing.JTable jtbUsu;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    public static javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
